# Config for DECT NR+ MCS 4
CONFIG_OPENTHREAD_OVER_DECTNR_DEFAULT_TX_MCS=4

# Enable ZPerf
CONFIG_NET_SOCKETS_OFFLOAD=n
CONFIG_NET_SHELL=y
CONFIG_NET_ZPERF=y
CONFIG_NET_CONTEXT_RCVTIMEO=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_SOCKETS_POLL_MAX=9
CONFIG_NET_CONTEXT_SNDTIMEO=y
#CONFIG_NET_TCP=y
#CONFIG_NET_TCP_ISN_RFC6528=n
CONFIG_POSIX_MAX_FDS=16
CONFIG_NET_TC_TX_COUNT=1

CONFIG_NET_PKT_RX_COUNT=20
CONFIG_NET_PKT_TX_COUNT=20
CONFIG_NET_BUF_RX_COUNT=20
CONFIG_NET_BUF_TX_COUNT=20

CONFIG_MAIN_STACK_SIZE=8192
CONFIG_NET_TX_STACK_SIZE=8192
CONFIG_NET_RX_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=8192
CONFIG_ZVFS_OPEN_MAX=20
CONFIG_POSIX_MAX_FDS=20
CONFIG_NET_SOCKETS_POLL_MAX=20
CONFIG_OT_DECT_RX_BUFFERS=40